///|
pub extend AutoTileCell with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileCell with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AutoTileCell with Eq::{not_equal, equal}

///|
pub extend AutoTileCell with ToJson::{to_json}

///|
pub extend AutoTileDiff with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileDiff with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AutoTileDiff with Eq::{not_equal, equal}

///|
pub extend AutoTileDiff with ToJson::{to_json}

///|
pub extend AutoTileGridPos with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileGridPos with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AutoTileGridPos with Eq::{not_equal, equal}

///|
pub extend AutoTileGridPos with ToJson::{to_json}

///|
pub extend AutoTileLayerSource with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileLayerSource with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AutoTileLayerSource with Eq::{not_equal, equal}

///|
pub extend AutoTileLayerSource with ToJson::{to_json}

///|
pub extend AutoTileMaskRule with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileMaskRule with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AutoTileMaskRule with Eq::{not_equal, equal}

///|
pub extend AutoTileMaskRule with ToJson::{to_json}

///|
pub extend AutoTilePaletteEntry with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTilePaletteEntry with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AutoTilePaletteEntry with Eq::{not_equal, equal}

///|
pub extend AutoTilePaletteEntry with ToJson::{to_json}

///|
pub extend AutoTileRuleSetKind with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileRuleSetKind with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AutoTileRuleSetKind with Eq::{not_equal, equal}

///|
pub extend AutoTileRuleSetKind with ToJson::{to_json}

///|
pub extend AutoTileSolvedTile with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileSolvedTile with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AutoTileSolvedTile with Eq::{not_equal, equal}

///|
pub extend AutoTileSolvedTile with ToJson::{to_json}

///|
pub extend AutoTileWangRule with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileWangRule with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AutoTileWangRule with Eq::{not_equal, equal}

///|
pub extend AutoTileWangRule with ToJson::{to_json}
