///|
pub extend Camera with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Camera with Default::{default}

///|
pub extend Camera with Eq::{not_equal, equal}

///|
pub extend Camera2d with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Camera2d with Default::{default}

///|
pub extend Camera2d with Eq::{not_equal, equal}

///|
pub extend CameraPass2D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CameraPass2D with Eq::{not_equal, equal}

///|
pub extend CameraPassLoadOp2D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CameraPassLoadOp2D with Eq::{not_equal, equal}

///|
pub extend CameraPassTarget2D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CameraPassTarget2D with Eq::{not_equal, equal}

///|
pub extend CameraViewport with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CameraViewport with Eq::{not_equal, equal}

///|
pub extend OrthographicProjection with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend OrthographicProjection with Default::{default}

///|
pub extend OrthographicProjection with Eq::{not_equal, equal}
