///|
pub extend Area with Eq::{not_equal, equal}

///|
pub extend Collider with Eq::{not_equal, equal}

///|
pub extend CollisionFilter with Eq::{not_equal, equal}

///|
pub extend CollisionGroup with Eq::{not_equal, equal}

///|
pub extend CollisionShape with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CollisionShape with Eq::{not_equal, equal}

///|
pub extend Joint with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Joint with Eq::{not_equal, equal}

///|
pub extend JointKind with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend JointKind with Eq::{not_equal, equal}

///|
pub extend JointLimits with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend JointLimits with Eq::{not_equal, equal}

///|
pub extend JointMotor with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend JointMotor with Eq::{not_equal, equal}

///|
pub extend JointMotorModel with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend JointMotorModel with Eq::{not_equal, equal}

///|
pub extend JointSoftness with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend JointSoftness with Eq::{not_equal, equal}

///|
pub extend MultibodyJoint with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MultibodyJoint with Eq::{not_equal, equal}

///|
pub extend MultibodyJointKind with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MultibodyJointKind with Eq::{not_equal, equal}

///|
pub extend PointerPhase with Eq::{not_equal, equal}

///|
pub extend RaycastHit with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RaycastHit with Eq::{not_equal, equal}

///|
pub extend RigidBody with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RigidBody with Eq::{not_equal, equal}

///|
pub extend RigidBodyType with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RigidBodyType with Eq::{not_equal, equal}

///|
pub extend ShapeCastHit with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ShapeCastHit with Eq::{not_equal, equal}

///|
pub extend SpatialQueryBodyFilter with Eq::{not_equal, equal}

///|
pub extend SpatialQueryFilter with Eq::{not_equal, equal}
