///|
pub extend Ccd with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Ccd with Eq::{not_equal, equal}

///|
pub extend Collider with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Collider with Eq::{not_equal, equal}

///|
pub extend ColliderMassProperties with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ColliderMassProperties with Eq::{not_equal, equal}

///|
pub extend CollisionEvent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CollisionEvent with Eq::{not_equal, equal}

///|
pub extend CollisionGroups with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CollisionGroups with Eq::{not_equal, equal}

///|
pub extend ContactForceEvent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ContactForceEvent with Eq::{not_equal, equal}

///|
pub extend ContactForceEventThreshold with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend ContactForceEventThreshold with Eq::{not_equal, equal}

///|
pub extend Damping with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Damping with Eq::{not_equal, equal}

///|
pub extend Dominance with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Dominance with Eq::{not_equal, equal}

///|
pub extend FixedJoint with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FixedJoint with Eq::{not_equal, equal}

///|
pub extend Friction with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Friction with Eq::{not_equal, equal}

///|
pub extend GravityScale with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend GravityScale with Eq::{not_equal, equal}

///|
pub extend KinematicCharacterControllerCollision with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend KinematicCharacterControllerCollision with Eq::{not_equal, equal}

///|
pub extend KinematicCharacterControllerCollisions with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend KinematicCharacterControllerCollisions with Eq::{not_equal, equal}

///|
pub extend KinematicCharacterControllerOutput with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend KinematicCharacterControllerOutput with Eq::{not_equal, equal}

///|
pub extend LockedAxes with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LockedAxes with Eq::{not_equal, equal}

///|
pub extend PointProjection with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PointProjection with Eq::{not_equal, equal}

///|
pub extend PrismaticJoint with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PrismaticJoint with Eq::{not_equal, equal}

///|
pub extend QueryFilterBody with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend QueryFilterBody with Eq::{not_equal, equal}

///|
pub extend RaycastHit with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RaycastHit with Eq::{not_equal, equal}

///|
pub extend Restitution with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Restitution with Eq::{not_equal, equal}

///|
pub extend RigidBody with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RigidBody with Eq::{not_equal, equal}

///|
pub extend RopeJoint with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RopeJoint with Eq::{not_equal, equal}

///|
pub extend Sensor with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Sensor with Eq::{not_equal, equal}

///|
pub extend SensorEvent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SensorEvent with Eq::{not_equal, equal}

///|
pub extend ShapeCastHit with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ShapeCastHit with Eq::{not_equal, equal}

///|
pub extend SolverGroups with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SolverGroups with Eq::{not_equal, equal}

///|
pub extend SphericalJoint with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SphericalJoint with Eq::{not_equal, equal}

///|
pub extend SpringJoint with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SpringJoint with Eq::{not_equal, equal}

///|
pub extend Velocity with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Velocity with Eq::{not_equal, equal}
