///|
pub extend AlphaMode3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AlphaMode3D with Eq::{not_equal, equal}

///|
pub extend CameraProjection3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CameraProjection3D with Eq::{not_equal, equal}

///|
pub extend CascadeShadowConfig3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CascadeShadowConfigBuilder3D with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend CascadeShadowConfigBuilder3D with Eq::{not_equal, equal}

///|
pub extend CubemapAsset3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CubemapAsset3D with Eq::{not_equal, equal}

///|
pub extend CubemapFaces3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CubemapFaces3D with Eq::{not_equal, equal}

///|
pub extend CubemapHandle with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CubemapHandle with Eq::{not_equal, equal}

///|
pub extend CubemapHandle with Hash::{hash, hash_combine}

///|
pub extend DirectionalLightShadowMap3D with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend DirectionalLightShadowMap3D with Eq::{not_equal, equal}

///|
pub extend FrameTransform3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FrameTransform3D with Eq::{not_equal, equal}

///|
pub extend ImageAsset with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ImageAsset with Eq::{not_equal, equal}

///|
pub extend ImageHandle with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ImageHandle with Eq::{not_equal, equal}

///|
pub extend ImageHandle with Hash::{hash, hash_combine}

///|
pub extend MaterialHandle with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MaterialHandle with Eq::{not_equal, equal}

///|
pub extend MaterialHandle with Hash::{hash, hash_combine}

///|
pub extend MeshAsset with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MeshAsset with Eq::{not_equal, equal}

///|
pub extend MeshHandle with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MeshHandle with Eq::{not_equal, equal}

///|
pub extend MeshHandle with Hash::{hash, hash_combine}

///|
pub extend MeshPrimitive3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MeshPrimitive3D with Eq::{not_equal, equal}

///|
pub extend PointLightShadowMap3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PointLightShadowMap3D with Eq::{not_equal, equal}

///|
pub extend RenderLine3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RenderLine3D with Eq::{not_equal, equal}

///|
pub extend SceneHandle with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SceneHandle with Eq::{not_equal, equal}

///|
pub extend SceneHandle with Hash::{hash, hash_combine}

///|
pub extend Skybox3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Skybox3D with Eq::{not_equal, equal}

///|
pub extend Tangent3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Tangent3D with Eq::{not_equal, equal}

///|
pub extend TextureBinding3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TextureBinding3D with Eq::{not_equal, equal}

///|
pub extend TextureFilter3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TextureFilter3D with Eq::{not_equal, equal}

///|
pub extend TextureSampler3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TextureSampler3D with Eq::{not_equal, equal}

///|
pub extend TextureTransform3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TextureTransform3D with Eq::{not_equal, equal}

///|
pub extend TextureWrap3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TextureWrap3D with Eq::{not_equal, equal}

///|
pub extend TriangleMesh3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TriangleMesh3D with Eq::{not_equal, equal}

///|
pub extend TriangleTopology3D with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TriangleTopology3D with Eq::{not_equal, equal}
