///|
pub extend InheritedVisibility with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend InheritedVisibility with Eq::{not_equal, equal}

///|
pub extend RenderLayers with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RenderLayers with Eq::{not_equal, equal}

///|
pub extend ViewVisibility with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ViewVisibility with Eq::{not_equal, equal}

///|
pub extend Visibility with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Visibility with Eq::{not_equal, equal}
