///|
pub extend AnimationClipAssetDocument with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AnimationClipAssetDocument with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationClipAssetDocument with Eq::{not_equal, equal}

///|
pub extend AnimationClipAssetDocument with ToJson::{to_json}

///|
pub extend AnimationClipAssetDocumentLoadStatus with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationClipAssetDocumentLoadStatus with Eq::{not_equal, equal}

///|
pub extend AnimationClipAssetDocumentLoadStatus with ToJson::{to_json}

///|
pub extend AnimationClipAssetMigrationPreview with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationClipAssetMigrationPreview with Eq::{not_equal, equal}

///|
pub extend AnimationClipAssetMigrationPreview with ToJson::{to_json}

///|
pub extend AnimationGraphAssetDocument with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AnimationGraphAssetDocument with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationGraphAssetDocument with Eq::{not_equal, equal}

///|
pub extend AnimationGraphAssetDocument with ToJson::{to_json}

///|
pub extend AnimationGraphAssetDocumentLoadStatus with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationGraphAssetDocumentLoadStatus with Eq::{not_equal, equal}

///|
pub extend AnimationGraphAssetDocumentLoadStatus with ToJson::{to_json}

///|
pub extend AnimationGraphAssetMigrationPreview with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationGraphAssetMigrationPreview with Eq::{not_equal, equal}

///|
pub extend AnimationGraphAssetMigrationPreview with ToJson::{to_json}

///|
pub extend AnimationGraphEdgeDocument with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AnimationGraphEdgeDocument with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationGraphEdgeDocument with Eq::{not_equal, equal}

///|
pub extend AnimationGraphEdgeDocument with ToJson::{to_json}

///|
pub extend AnimationGraphNodeDocument with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AnimationGraphNodeDocument with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationGraphNodeDocument with Eq::{not_equal, equal}

///|
pub extend AnimationGraphNodeDocument with ToJson::{to_json}

///|
pub extend AnimationGraphNodeKind with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AnimationGraphNodeKind with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationGraphNodeKind with Eq::{not_equal, equal}

///|
pub extend AnimationGraphNodeKind with ToJson::{to_json}

///|
pub extend AnimationPlayerComponent with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AnimationPlayerComponent with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationPlayerComponent with Eq::{not_equal, equal}

///|
pub extend AnimationPlayerComponent with ToJson::{to_json}

///|
pub extend AnimationRepeatModeDoc with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AnimationRepeatModeDoc with Eq::{not_equal, equal}

///|
pub extend AnimationTransitionsComponent with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AnimationTransitionsComponent with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationTransitionsComponent with Eq::{not_equal, equal}

///|
pub extend AnimationTransitionsComponent with ToJson::{to_json}

///|
pub extend AssetDocument with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AssetDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AssetDocument with Eq::{not_equal, equal}

///|
pub extend AssetDocument with ToJson::{to_json}

///|
pub extend AssetKind with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AssetKind with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AssetKind with Eq::{not_equal, equal}

///|
pub extend AssetKind with ToJson::{to_json}

///|
pub extend AssetMetaDocument with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AssetMetaDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AssetMetaDocument with Eq::{not_equal, equal}

///|
pub extend AssetMetaDocument with ToJson::{to_json}

///|
pub extend AssetRef with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AssetRef with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AssetRef with Eq::{not_equal, equal}

///|
pub extend AssetRef with ToJson::{to_json}

///|
pub extend AtlasAssetDocument with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AtlasAssetDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AtlasAssetDocument with Eq::{not_equal, equal}

///|
pub extend AtlasAssetDocument with ToJson::{to_json}

///|
pub extend AtlasAssetDocumentLoadStatus with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AtlasAssetDocumentLoadStatus with Eq::{not_equal, equal}

///|
pub extend AtlasAssetDocumentLoadStatus with ToJson::{to_json}

///|
pub extend AtlasAssetMigrationPreview with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AtlasAssetMigrationPreview with Eq::{not_equal, equal}

///|
pub extend AtlasAssetMigrationPreview with ToJson::{to_json}

///|
pub extend AtlasRegionDocument with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AtlasRegionDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AtlasRegionDocument with Eq::{not_equal, equal}

///|
pub extend AtlasRegionDocument with ToJson::{to_json}

///|
pub extend AutoTileCellDocument with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileCellDocument with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AutoTileCellDocument with Eq::{not_equal, equal}

///|
pub extend AutoTileCellDocument with ToJson::{to_json}

///|
pub extend AutoTileLayer2dComponent with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AutoTileLayer2dComponent with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AutoTileLayer2dComponent with Eq::{not_equal, equal}

///|
pub extend AutoTileLayer2dComponent with ToJson::{to_json}

///|
pub extend AutoTileMaskRuleDocument with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AutoTileMaskRuleDocument with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AutoTileMaskRuleDocument with Eq::{not_equal, equal}

///|
pub extend AutoTileMaskRuleDocument with ToJson::{to_json}

///|
pub extend AutoTilePaletteEntryDocument with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AutoTilePaletteEntryDocument with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AutoTilePaletteEntryDocument with Eq::{not_equal, equal}

///|
pub extend AutoTilePaletteEntryDocument with ToJson::{to_json}

///|
pub extend AutoTileRuleSetDocument with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AutoTileRuleSetDocument with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AutoTileRuleSetDocument with Eq::{not_equal, equal}

///|
pub extend AutoTileRuleSetDocument with ToJson::{to_json}

///|
pub extend AutoTileWangRuleDocument with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend AutoTileWangRuleDocument with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AutoTileWangRuleDocument with Eq::{not_equal, equal}

///|
pub extend AutoTileWangRuleDocument with ToJson::{to_json}

///|
pub extend BuiltinComponentKind with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BuiltinComponentKind with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend BuiltinComponentKind with Eq::{not_equal, equal}

///|
pub extend BuiltinComponentKind with ToJson::{to_json}

///|
pub extend Camera2dComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Camera2dComponent with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend Camera2dComponent with Eq::{not_equal, equal}

///|
pub extend Camera2dComponent with ToJson::{to_json}

///|
pub extend ColorDoc with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ColorDoc with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ColorDoc with Eq::{not_equal, equal}

///|
pub extend ColorDoc with ToJson::{to_json}

///|
pub extend ColorMaterialComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ColorMaterialComponent with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend ColorMaterialComponent with Eq::{not_equal, equal}

///|
pub extend ColorMaterialComponent with ToJson::{to_json}

///|
pub extend ComponentDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ComponentDocument with Eq::{not_equal, equal}

///|
pub extend ComponentDocument with ToJson::{to_json}

///|
pub extend DocumentEnvelope with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend DocumentEnvelope with Eq::{not_equal, equal}

///|
pub extend DocumentEnvelope with ToJson::{to_json}

///|
pub extend EntityDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend EntityDocument with Eq::{not_equal, equal}

///|
pub extend EntityDocument with ToJson::{to_json}

///|
pub extend Mesh2dComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Mesh2dComponent with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend Mesh2dComponent with Eq::{not_equal, equal}

///|
pub extend Mesh2dComponent with ToJson::{to_json}

///|
pub extend MigrationFieldChange with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend MigrationFieldChange with Eq::{not_equal, equal}

///|
pub extend MigrationFieldChange with ToJson::{to_json}

///|
pub extend NameComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend NameComponent with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend NameComponent with Eq::{not_equal, equal}

///|
pub extend NameComponent with ToJson::{to_json}

///|
pub extend PhysicsBody2dComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PhysicsBody2dComponent with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend PhysicsBody2dComponent with Eq::{not_equal, equal}

///|
pub extend PhysicsBody2dComponent with ToJson::{to_json}

///|
pub extend PhysicsCollider2dComponent with @moonbitlang/core/debug.Debug::{
  to_repr,
}

///|
pub extend PhysicsCollider2dComponent with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend PhysicsCollider2dComponent with Eq::{not_equal, equal}

///|
pub extend PhysicsCollider2dComponent with ToJson::{to_json}

///|
pub extend PrefabDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend PrefabDocument with Eq::{not_equal, equal}

///|
pub extend PrefabDocument with ToJson::{to_json}

///|
pub extend PrefabDocumentLoadStatus with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend PrefabDocumentLoadStatus with Eq::{not_equal, equal}

///|
pub extend PrefabDocumentLoadStatus with ToJson::{to_json}

///|
pub extend PrefabMigrationPreview with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend PrefabMigrationPreview with Eq::{not_equal, equal}

///|
pub extend PrefabMigrationPreview with ToJson::{to_json}

///|
pub extend PrefabRef with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PrefabRef with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend PrefabRef with Eq::{not_equal, equal}

///|
pub extend PrefabRef with ToJson::{to_json}

///|
pub extend ProjectBundle with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ProjectBundle with Eq::{not_equal, equal}

///|
pub extend ProjectBundle with ToJson::{to_json}

///|
pub extend ProjectManifest with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ProjectManifest with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ProjectManifest with Eq::{not_equal, equal}

///|
pub extend ProjectManifest with ToJson::{to_json}

///|
pub extend ProjectManifestLoadStatus with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend ProjectManifestLoadStatus with Eq::{not_equal, equal}

///|
pub extend ProjectManifestLoadStatus with ToJson::{to_json}

///|
pub extend ProjectManifestMigrationPreview with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend ProjectManifestMigrationPreview with Eq::{not_equal, equal}

///|
pub extend ProjectManifestMigrationPreview with ToJson::{to_json}

///|
pub extend RectDoc with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RectDoc with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend RectDoc with Eq::{not_equal, equal}

///|
pub extend RectDoc with ToJson::{to_json}

///|
pub extend SceneDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend SceneDocument with Eq::{not_equal, equal}

///|
pub extend SceneDocument with ToJson::{to_json}

///|
pub extend SceneDocumentLoadStatus with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend SceneDocumentLoadStatus with Eq::{not_equal, equal}

///|
pub extend SceneDocumentLoadStatus with ToJson::{to_json}

///|
pub extend SceneMigrationPreview with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend SceneMigrationPreview with Eq::{not_equal, equal}

///|
pub extend SceneMigrationPreview with ToJson::{to_json}

///|
pub extend ScenePatch with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ScenePatch with Eq::{not_equal, equal}

///|
pub extend ScenePatch with ToJson::{to_json}

///|
pub extend ScenePatchOp with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ScenePatchOp with Eq::{not_equal, equal}

///|
pub extend ScenePatchOp with ToJson::{to_json}

///|
pub extend SceneRef with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SceneRef with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend SceneRef with Eq::{not_equal, equal}

///|
pub extend SceneRef with ToJson::{to_json}

///|
pub extend SpriteComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SpriteComponent with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend SpriteComponent with Eq::{not_equal, equal}

///|
pub extend SpriteComponent with ToJson::{to_json}

///|
pub extend Text2dComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Text2dComponent with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend Text2dComponent with Eq::{not_equal, equal}

///|
pub extend Text2dComponent with ToJson::{to_json}

///|
pub extend TextureAtlasComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TextureAtlasComponent with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend TextureAtlasComponent with Eq::{not_equal, equal}

///|
pub extend TextureAtlasComponent with ToJson::{to_json}

///|
pub extend TextureAtlasLayoutDoc with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TextureAtlasLayoutDoc with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend TextureAtlasLayoutDoc with Eq::{not_equal, equal}

///|
pub extend TextureAtlasLayoutDoc with ToJson::{to_json}

///|
pub extend Transform2dComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Transform2dComponent with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend Transform2dComponent with Eq::{not_equal, equal}

///|
pub extend Transform2dComponent with ToJson::{to_json}

///|
pub extend ValidationError with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ValidationError with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ValidationError with Eq::{not_equal, equal}

///|
pub extend ValidationError with ToJson::{to_json}

///|
pub extend Vec2Doc with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Vec2Doc with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend Vec2Doc with Eq::{not_equal, equal}

///|
pub extend Vec2Doc with ToJson::{to_json}

///|
pub extend VisibilityComponent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend VisibilityComponent with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend VisibilityComponent with Eq::{not_equal, equal}

///|
pub extend VisibilityComponent with ToJson::{to_json}

///|
pub extend WorkspaceDocument with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend WorkspaceDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend WorkspaceDocument with Eq::{not_equal, equal}

///|
pub extend WorkspaceDocument with ToJson::{to_json}
