///|
pub let project_schema_version = 2

///|
pub let scene_schema_version = 3

///|
pub let scene_legacy_schema_version = 2

///|
pub let prefab_schema_version = 2

///|
pub let atlas_asset_schema_version = 2

///|
pub let animation_clip_asset_schema_version = 3

///|
pub let animation_graph_asset_schema_version = 3

///|
pub let legacy_animation_asset_schema_version = 2

///|
pub let workspace_schema_version = 2
