///|
pub fn msg_create_atlas_from_selected_image() -> Msg {
  CreateAtlasFromSelectedImage
}

///|
pub fn msg_create_animation_from_selected_atlas() -> Msg {
  CreateAnimationFromSelectedAtlas
}

///|
pub fn msg_create_animation_graph_from_selected_clip() -> Msg {
  CreateAnimationGraphFromSelectedClip
}

///|
pub fn msg_save_selected_as_prefab() -> Msg {
  SaveSelectedAsPrefab
}

///|
pub fn msg_insert_selected_resource() -> Msg {
  InsertSelectedResource
}
