///|
pub extend AssetScope with Eq::{not_equal, equal}

///|
pub extend Effect with Eq::{not_equal, equal}

///|
pub extend Model with Eq::{not_equal, equal}

///|
pub extend ResourceSelection with Eq::{not_equal, equal}

///|
pub extend RpcBinding with Eq::{not_equal, equal}

///|
pub extend SceneConflictState with Eq::{not_equal, equal}

///|
pub extend SceneEditTransaction with Eq::{not_equal, equal}

///|
pub extend SceneSaveOutcome with Eq::{not_equal, equal}

///|
pub extend SceneSession with Eq::{not_equal, equal}

///|
pub extend ViewState with Eq::{not_equal, equal}
