///|
pub extend AlignContent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AlignContent with Eq::{not_equal, equal}

///|
pub extend AlignItems with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend AlignItems with Eq::{not_equal, equal}

///|
pub extend BorderRadius with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BorderRadius with Eq::{not_equal, equal}

///|
pub extend BoxShadow with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BoxShadow with Eq::{not_equal, equal}

///|
pub extend Button with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Button with Eq::{not_equal, equal}

///|
pub extend Display with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Display with Eq::{not_equal, equal}

///|
pub extend FlexDirection with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FlexDirection with Eq::{not_equal, equal}

///|
pub extend FlexWrap with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FlexWrap with Eq::{not_equal, equal}

///|
pub extend FocusPolicy with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FocusPolicy with Eq::{not_equal, equal}

///|
pub extend GlobalZIndex with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend GlobalZIndex with Eq::{not_equal, equal}

///|
pub extend GridAutoFlow with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend GridAutoFlow with Eq::{not_equal, equal}

///|
pub extend GridLine with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend GridLine with Eq::{not_equal, equal}

///|
pub extend GridPlacement with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend GridPlacement with Eq::{not_equal, equal}

///|
pub extend GridTrack with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend GridTrack with Eq::{not_equal, equal}

///|
pub extend GridTrackRepetition with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend GridTrackRepetition with Eq::{not_equal, equal}

///|
pub extend ImageFit with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ImageFit with Eq::{not_equal, equal}

///|
pub extend Interaction with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Interaction with Eq::{not_equal, equal}

///|
pub extend JustifyContent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend JustifyContent with Eq::{not_equal, equal}

///|
pub extend LayoutConfig with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend LayoutConfig with Eq::{not_equal, equal}

///|
pub extend MaterialNode with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MaterialNode with Eq::{not_equal, equal}

///|
pub extend Node with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Node with Eq::{not_equal, equal}

///|
pub extend Overflow with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Overflow with Eq::{not_equal, equal}

///|
pub extend OverflowClipBox with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend OverflowClipBox with Eq::{not_equal, equal}

///|
pub extend OverflowClipMargin with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend OverflowClipMargin with Eq::{not_equal, equal}

///|
pub extend OverrideClip with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend OverrideClip with Eq::{not_equal, equal}

///|
pub extend PositionType with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PositionType with Eq::{not_equal, equal}

///|
pub extend RelativeCursorPosition with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend RelativeCursorPosition with Eq::{not_equal, equal}

///|
pub extend ScrollPosition with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ScrollPosition with Eq::{not_equal, equal}

///|
pub extend ShadowStyle with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ShadowStyle with Eq::{not_equal, equal}

///|
pub extend TabIndex with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TabIndex with Eq::{not_equal, equal}

///|
pub extend TextOverflow with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TextOverflow with Eq::{not_equal, equal}

///|
pub extend TextWrap with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TextWrap with Eq::{not_equal, equal}

///|
pub extend UiGradient with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UiGradient with Eq::{not_equal, equal}

///|
pub extend UiImage with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UiImage with Eq::{not_equal, equal}

///|
pub extend UiInsets with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UiInsets with Eq::{not_equal, equal}

///|
pub extend UiMaterialHandle with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UiMaterialHandle with Eq::{not_equal, equal}

///|
pub extend UiMaterialHandle with Hash::{hash, hash_combine}

///|
pub extend UiNavigationDirection with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UiNavigationDirection with Eq::{not_equal, equal}

///|
pub extend UiRectValues with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UiRectValues with Eq::{not_equal, equal}

///|
pub extend UiScaleMode with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UiScaleMode with Eq::{not_equal, equal}

///|
pub extend UiTargetCamera with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend UiTargetCamera with Eq::{not_equal, equal}

///|
pub extend Val with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Val with Eq::{not_equal, equal}

///|
pub extend ZIndex with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ZIndex with Eq::{not_equal, equal}
