///|
pub extend AnimationClipLoadResponse with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationClipLoadResponse with Eq::{not_equal, equal}

///|
pub extend AnimationClipLoadResponse with ToJson::{to_json}

///|
pub extend AnimationGraphLoadResponse with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend AnimationGraphLoadResponse with Eq::{not_equal, equal}

///|
pub extend AnimationGraphLoadResponse with ToJson::{to_json}

///|
pub extend AssetsListResponse with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AssetsListResponse with Eq::{not_equal, equal}

///|
pub extend AssetsListResponse with ToJson::{to_json}

///|
pub extend AtlasLoadResponse with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend AtlasLoadResponse with Eq::{not_equal, equal}

///|
pub extend AtlasLoadResponse with ToJson::{to_json}

///|
pub extend DirectoryPickResult with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend DirectoryPickResult with Eq::{not_equal, equal}

///|
pub extend DirectoryPickResult with ToJson::{to_json}

///|
pub extend EditorEvent with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend EditorEvent with Eq::{not_equal, equal}

///|
pub extend EditorEvent with ToJson::{to_json}

///|
pub extend EventEnvelope with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend EventEnvelope with Eq::{not_equal, equal}

///|
pub extend EventEnvelope with ToJson::{to_json}

///|
pub extend PrefabLoadResponse with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend PrefabLoadResponse with Eq::{not_equal, equal}

///|
pub extend PrefabLoadResponse with ToJson::{to_json}

///|
pub extend PreviewTool with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend PreviewTool with Eq::{not_equal, equal}

///|
pub extend PreviewTool with ToJson::{to_json}

///|
pub extend ProjectDeltaEvent with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend ProjectDeltaEvent with Eq::{not_equal, equal}

///|
pub extend ProjectDeltaEvent with ToJson::{to_json}

///|
pub extend ProjectStateResponse with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend ProjectStateResponse with Eq::{not_equal, equal}

///|
pub extend ProjectStateResponse with ToJson::{to_json}

///|
pub extend RpcConflictDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend RpcConflictDocument with Eq::{not_equal, equal}

///|
pub extend RpcConflictDocument with ToJson::{to_json}

///|
pub extend RpcErrorDocument with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend RpcErrorDocument with Eq::{not_equal, equal}

///|
pub extend RpcErrorDocument with ToJson::{to_json}

///|
pub extend RpcRequest with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend RpcRequest with Eq::{not_equal, equal}

///|
pub extend RpcRequest with ToJson::{to_json}

///|
pub extend RpcRequestEnvelope with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend RpcRequestEnvelope with Eq::{not_equal, equal}

///|
pub extend RpcRequestEnvelope with ToJson::{to_json}

///|
pub extend RpcResponse with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend RpcResponse with Eq::{not_equal, equal}

///|
pub extend RpcResponse with ToJson::{to_json}

///|
pub extend RpcResponseEnvelope with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend RpcResponseEnvelope with Eq::{not_equal, equal}

///|
pub extend RpcResponseEnvelope with ToJson::{to_json}

///|
pub extend SceneBundleAnimationClipEntry with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend SceneBundleAnimationClipEntry with Eq::{not_equal, equal}

///|
pub extend SceneBundleAnimationClipEntry with ToJson::{to_json}

///|
pub extend SceneBundleAnimationGraphEntry with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend SceneBundleAnimationGraphEntry with Eq::{not_equal, equal}

///|
pub extend SceneBundleAnimationGraphEntry with ToJson::{to_json}

///|
pub extend SceneBundleAtlasEntry with @moonbitlang/core/json.FromJson::{
  from_json,
}

///|
pub extend SceneBundleAtlasEntry with Eq::{not_equal, equal}

///|
pub extend SceneBundleAtlasEntry with ToJson::{to_json}

///|
pub extend SceneBundleResponse with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend SceneBundleResponse with Eq::{not_equal, equal}

///|
pub extend SceneBundleResponse with ToJson::{to_json}

///|
pub extend SceneListResponse with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend SceneListResponse with Eq::{not_equal, equal}

///|
pub extend SceneListResponse with ToJson::{to_json}

///|
pub extend SceneLoadOutcome with Eq::{not_equal, equal}

///|
pub extend SceneSaveResult with @moonbitlang/core/json.FromJson::{from_json}

///|
pub extend SceneSaveResult with Eq::{not_equal, equal}

///|
pub extend SceneSaveResult with ToJson::{to_json}
